[package]
name = "lapnier"
version = "0.1.0"
edition = "2021"

[dependencies]
limine = "0.3.1"

[dependencies.arrayvec]
version = "0.7.6"
default_features = false

[profile.dev]
panic = "unwind"

[profile.release]
panic = "abort"
