[package]
name = "lapnier"
version = "0.0.0-alpha"
edition = "2021"

[dependencies]
limine = "0.3.1"

[dependencies.arrayvec]
version = "0.7.6"
default-features = false

[build-dependencies]
cc = "1.0"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "abort"
